# Generated by Django 5.2.4 on 2025-09-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='dummyfield',
            field=models.TextField(default='n/a'),
        ),
        migrations.AddField(
            model_name='review',
            name='dummyfield',
            field=models.TextField(default='n/a'),
        ),
    ]
